openapi: 3.0.1
info:
  title: D20 Roll Plugin
  description: Roll any die from an external oracle using the 'sides' parameter.
  version: '1.1.0'
servers:
  - url: https://dmb-rolld20.netlify.app
paths:
  /.netlify/functions/roll-d20:
    get:
      operationId: getDiceRoll
      summary: Roll a custom die (d4, d6, d20, etc.)
      parameters:
        - name: sides
          in: query
          required: false
          description: Number of sides on the die (e.g., 4, 6, 20). Defaults to 20.
          schema:
            type: integer
            minimum: 2
            maximum: 100
            example: 20
      responses:
        '200':
          description: A random die roll result
          content:
            application/json:
              schema:
                type: object
                properties:
                  roll:
                    type: integer
                    example: 17
                  sides:
                    type: integer
                    example: 20
        '400':
          description: Invalid input (e.g. sides too low/high or missing)
